### ISSUE TITLE
Fix for very slow encryption

### ISSUE THREAD

**Issue by jonathanbromley** [nick322/secure-spreadsheet#10]
I reported a while ago (issue #7 ) that encryption seems unreasonably slow. The new version appears to be nearly 2X faster but is still unacceptably slow.

I have now tracked this down and it seems that a VERY large proportion of the runtime is spent in function _convertPasswordToKey which runs 100000 iterations of a hash function. It does this by calling function _hash repeatedly in an extremely inefficient way:

- unnecessary repeated checks that the algorithm string is correct (not very important for performance, but completely unnecessary)
- futile pack() and unpack() calls at the beginning and end of each call to _hash(). I'm sure this is the performance killer.
- function _createUInt32LEBuffer seems unnecessarily clumsy (again, probably not a big deal for performance)
- use of incremental hash_init/hash_update/hash_final is probably slightly less efficient than a simple call to hash()

It is pretty easy to rewrite _convertPasswordToKey so that these inefficiencies are removed. Making these changes has NO impact on functionality, and improves the runtime of _convertPasswordToKey by **more than 10X.** The overall effect is to make the runtime of the whole encryption process become acceptable.

Sorry, I don't have the expertise with Git to submit a pull request, but the change is really tiny. Lines 404-408 of Encrypt.php are currently:
 ```
       // Now regenerate until spin count
        for ($i = 0; $i < $spinCount; $i++) {
            $iterator = $this->_createUInt32LEBuffer($i);
            $key = $this->_hash($hashAlgorithm, $iterator, $key);
        }
```

Those lines can be replaced with this code:
```
        // Prepare for hash(). Algo is known to be OK. Previous call to _hash()
        // would have thrown an exception if not.
        $algo = strtolower($hashAlgorithm);

        // Get back to a binary string
        $bKey = pack('C*', ...$key);

        // Now regenerate until spin count
        for ($i = 0; $i < $spinCount; $i++) {
          $bKey = hash($algo, pack('V',$i).$bKey, true);
        }

        // Convert binary string back to unpacked C* form
        $key = unpack('C*', $bKey);
```

I have tested this against the original function (by making them both public and running a side-by-side test on dummy data) and they appear to generate identical results. The encrypted files can be opened with Excel as expected.

I hope this is useful. I am already using the patch successfully in my own application.

**Comment by nick322** [comment]
@jonathanbromley Thank you very much for your contribution, I will revise your question as soon as possible.

**Comment by nick322** [comment]
@jonathanbromley 
When I tested this change it performed faster again. I have posted the latest version up.
Thank you for your contribution

**Comment by jonathanbromley** [comment]
Thank you for your super-prompt response!
