### ISSUE TITLE
Password is not accepted

### ISSUE THREAD

**Issue by m4tthumphrey** [nick322/secure-spreadsheet#18]
Hello,

I was hesitant about opening an issue, purely because I do not have any additional information, but when I try and use this, the file does indeed become encrypted but the password that gets set is not accepted. 

The code is simply this:

```php
(new Encrypt())
    ->input($filepath)
    ->password('abc123')
    ->output($filepath);
```

When I try and open the file:

<img width="269" alt="Screenshot 2023-09-19 at 14 00 56" src="https://github.com/nick322/secure-spreadsheet/assets/582971/fc8fe23f-7ac0-4581-9be4-13837c984fa2">

I am using PHPSpreadsheet to generate the file so I am guessing that will be part of it.

Am running on docker on macOS Ventura 13.5.2 (22G91), PHP 8.2.7 (cli) (built: Jun  8 2023 15:27:40) (NTS).

Not sure what sort of feedback I expect to get with such limited information but I am stumped!

**Comment by nick322** [comment]
Could you please provide your package version number, xlsx file, and current
php -m status, version of MS office. Thank you.

**Comment by m4tthumphrey** [comment]
`php -m`

```txt
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcov
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
random
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

```json
{
    "name": "nick322/secure-spreadsheet",
    "version": "1.0.9",
    "source": {
        "type": "git",
        "url": "https://github.com/nick322/secure-spreadsheet.git",
         "reference": "43b9f9cdf0fed0d633747204bd60165e6ca3eec6"
    }
}
```

<img width="379" alt="Screenshot 2023-09-19 at 17 32 34" src="https://github.com/nick322/secure-spreadsheet/assets/582971/33e07601-2929-40b2-9f1b-0937d380ffef">



Original file: [text.xlsx](https://github.com/nick322/secure-spreadsheet/files/12664403/text.xlsx)
Encrypted file: [encrypted.xlsx](https://github.com/nick322/secure-spreadsheet/files/12664404/encrypted.xlsx)
Password: `abc123`

**Comment by nick322** [comment]
@m4tthumphrey After investigation, it was found that it was an implementation issue caused by the change to hash. It has been changed back. You can use  1.0.10 version. Thank you for your report.

**Comment by m4tthumphrey** [comment]
Awesome! Works perfectly now. Thanks for fixing so quickly.
