### ISSUE TITLE
[Bug]: not working 

### ISSUE THREAD

**Issue by sonnhb** [nick322/secure-spreadsheet#24]
### Bug description

I using php 7.3 to test.
`PHP 7.3.33 (cli) (built: Nov 18 2021 20:26:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans`

but I have an error:
`/var/www/html/secure-spreadsheet # ./secure-spreadsheet run --password=1 --input=./Book1.xlsx --output=./bb.xlsx
PHP Warning:  require_once(PEAR.php): failed to open stream: No such file or directory in /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS.php on line 24
PHP Stack trace:
PHP   1. {main}() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:0
PHP   2. Silly\Application->run() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:29
PHP   3. Silly\Application->doRun() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:171
PHP   4. Silly\Application->doRunCommand() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:301
PHP   5. Silly\Command\Command->run() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:1040
PHP   6. Silly\Application->Silly\{closure:/var/www/html/secure-spreadsheet/vendor/mnapoli/silly/src/Application.php:72-99}() /var/www/html/secure-spreadsheet/vendor/symfony/console/Command/Command.php:296
PHP   7. Invoker\Invoker->call() /var/www/html/secure-spreadsheet/vendor/mnapoli/silly/src/Application.php:95
PHP   8. call_user_func_array:{/var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74}() /var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74
PHP   9. Silly\Application->{closure:/var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:20-26}() /var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74
PHP  10. Nick\SecureSpreadsheet\Encrypt->output() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:24
PHP  11. spl_autoload_call() /var/www/html/secure-spreadsheet/src/Encrypt.php:231
PHP  12. Composer\Autoload\ClassLoader->loadClass() /var/www/html/secure-spreadsheet/src/Encrypt.php:231
PHP  13. Composer\Autoload\{closure:/var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:575-577}() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:427
PHP  14. include() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:576
PHP  15. class_exists() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  16. spl_autoload_call() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  17. Composer\Autoload\ClassLoader->loadClass() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  18. Composer\Autoload\{closure:/var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:575-577}() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:427
PHP  19. include() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:576
PHP Fatal error:  require_once(): Failed opening required 'PEAR.php' (include_path='/var/www/html/secure-spreadsheet/vendor/pear/pear_exception:/var/www/html/secure-spreadsheet/vendor/pear/ole:.:') in /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS.php on line 24
PHP Stack trace:
PHP   1. {main}() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:0
PHP   2. Silly\Application->run() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:29
PHP   3. Silly\Application->doRun() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:171
PHP   4. Silly\Application->doRunCommand() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:301
PHP   5. Silly\Command\Command->run() /var/www/html/secure-spreadsheet/vendor/symfony/console/Application.php:1040
PHP   6. Silly\Application->Silly\{closure:/var/www/html/secure-spreadsheet/vendor/mnapoli/silly/src/Application.php:72-99}() /var/www/html/secure-spreadsheet/vendor/symfony/console/Command/Command.php:296
PHP   7. Invoker\Invoker->call() /var/www/html/secure-spreadsheet/vendor/mnapoli/silly/src/Application.php:95
PHP   8. call_user_func_array:{/var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74}() /var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74
PHP   9. Silly\Application->{closure:/var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:20-26}() /var/www/html/secure-spreadsheet/vendor/php-di/invoker/src/Invoker.php:74
PHP  10. Nick\SecureSpreadsheet\Encrypt->output() /var/www/html/secure-spreadsheet/src/secure-spreadsheet.php:24
PHP  11. spl_autoload_call() /var/www/html/secure-spreadsheet/src/Encrypt.php:231
PHP  12. Composer\Autoload\ClassLoader->loadClass() /var/www/html/secure-spreadsheet/src/Encrypt.php:231
PHP  13. Composer\Autoload\{closure:/var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:575-577}() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:427
PHP  14. include() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:576
PHP  15. class_exists() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  16. spl_autoload_call() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  17. Composer\Autoload\ClassLoader->loadClass() /var/www/html/secure-spreadsheet/vendor/pear/ole/OLE/PPS/File.php:23
PHP  18. Composer\Autoload\{closure:/var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:575-577}() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:427
PHP  19. include() /var/www/html/secure-spreadsheet/vendor/composer/ClassLoader.php:576`
what wrong with it?

**Comment by IMBigWillie** [comment]
I ran into the same issue. After I installed this it worked fine

https://pear.php.net/manual/en/installation.getting.php

**Comment by tronkko** [comment]
I was able to fix this by installing pear-core-minimal
```
composer require pear/pear-core-minimal
```

**Comment by gggeek** [comment]
Indeed something which should be fixed in pear/OLE (imho). Will send a PR for that

**Comment by gggeek** [comment]
Small update: as of today, neither my PR to par/OLE was merged (see https://github.com/pear/OLE/pull/33), nor a new version released. Also, the inquiry about the correct way to specify dependencies on pear core classes (the issue 142 I opened in pear/core) is unanswered...
