### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by LinasRam** [nick322/secure-spreadsheet#26]
Hi, @nick322,

As active support of PHP 8.2 version is coming to an end and 8.4 version is going to be released soon, is there a plan to add the support 8.3 or even 8.4 versions of PHP? I haven't checked if newer PHP version has any impact to current code, but it's very likely that it won't and just adding another PHP version to composer file will be enough.

Best regards,
Linas

**Comment by nick322** [comment]
done
