### ISSUE TITLE
In-memory encryption of a small spreadsheet seems very slow

### ISSUE THREAD

**Issue by jonathanbromley** [nick322/secure-spreadsheet#7]
I have a PHP application that creates an encrypted spreadsheet on demand. It uses the well-known PhpSpreadsheet package to create the spreadsheet, then uses SecureSpreadsheet to encrypt it. I'm sure many people do something very similar...

[EDIT: Sorry, forgot to mention the version of SecureSpreadsheet. It's v1.0.5, installed using Composer.]

```php
/* Do whatever it takes to build the sheet using PhpSpreadsheet. Then.... */
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($myNiceNewSpreadsheet, "Xlsx");
$encrypter = new Nick\SecureSpreadsheet\Encrypt(true);

// Output .xlsx file contents to memory (it's known to be very small, less than 100kB)
ob_start();
$writer->save('php://output');
$xlData = ob_get_clean();

// Now run SecureSpreadsheet if required
if ($password) {
  $xlData = $encrypter->input($xlData)->password($password)->output();
}

// Send headers and content
header('Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename='blahblah.xlsx');
header('Cache-Control: max-age=0');
echo $xlData;
die();
```
... and this takes well under a second if $password is false, but around 10 to 20 seconds if there's a password.

I know the encrypter has a LOT of work to do, but this seems excessive - the server I'm running on is pretty quick and almost never exhibits perceptible lag on various other tasks such as image manipulation.

Is it better to invoke the encrypter on a file rather than in-memory? Is there anything else I can do to speed things up?

Thanks in advance for any insights.

**Comment by nick322** [comment]
@jonathanbromley Versions after 1.0.5 have been rewritten for memory usage and OLE (Object Linking and Embedding), which should help improve performance. You can try again with latest version (1.0.7).

**Comment by jonathanbromley** [comment]
Thanks.

Looks like about 2X performance improvement from v1.0.7 compared to 1.0.5.  Much better, but it's still by far the slowest thing anywhere on my website! I'd be really interested to know where all the work is going and whether there are any mitigations. BTW I'm on PHP 8.2.8.

Given the complexities of encryption I wouldn't be surprised at this, but there's an interesting comparison: If you ask Excel to save a small spreadsheet with encryption, there is no noticeable time penalty.

Thanks for all the good work you're doing on this.

**Comment by gggeek** [comment]
By a cursory look at the code, it seems that there is still usage of a temp file involved, which might be slowing down the conversion a bit, but also represent a security issue.
I order to avoid touching the disk at all, one would have to add the capability of using streams to the Pear OLE component - see https://pear.php.net/bugs/bug.php?id=28646&
